name: Solar System Workflow v1

on:
  push:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch:

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}    
jobs:
  unit_testing:
    strategy:
      matrix:
        nodejs_version: [18,19,20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_system: macos-latest
    runs-on: ${{matrix.operating_system}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{matrix.nodejs_version}}
        uses: actions/setup-node@v3
        with:
          node-version: '${{matrix.nodejs_version}}'

      - name: cache dependencies
        uses: actions/cache@v3
        with:
            path: node_modules
            key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: uploadt test artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{matrix.operating_system}}app-test-result-${{matrix.nodejs_version}}
            path: test-results.xml
  
  
  code_coverage:
    strategy:
        matrix:
          nodejs_version: [18,19,20]
          operating_system: [ubuntu-latest, macos-latest]
          exclude:
            - nodejs_version: 18
              operating_system: macos-latest
    runs-on: ${{matrix.operating_system}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{matrix.nodejs_version}}
        uses: actions/setup-node@v3
        with:
          node-version: '${{matrix.nodejs_version}}'

      - name: cache dependencies
        uses: actions/cache@v3
        with:
            path: node_modules
            key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}

      - name: Install dependencies
        run: npm install

      - name: check code coverage
        continue-on-error: true
        run: npm run coverage

      - name: uploadt test artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{matrix.operating_system}}-code_coverage_result-${{matrix.nodejs_version}}
            path: test-results.xml
            